### ISSUE TITLE
windows系统分布式训练问题

### ISSUE THREAD

**Issue by gaokaizhi** [lemuria-wchen/DialogVED#1]
您好，我是用单机多卡进行分布式训练，但是报了这个错Runtimeerror: no rendezvous handler for TCP: / /，请问应该修改哪里才能解决呢

**Comment by lemuria-wchen** [comment]
你好，能否具体一点，开发环境之类的，torch   ，cuda版本之类的，能否都贴出来一下---- 回复的原邮件 ***@***.***>发送日期2022年10月11日 09:30 ***@***.***> ***@***.***>主题[lemuria-wchen/DialogVED] windows系统分布式训练问题 (Issue #1)

您好，我是用单机多卡进行分布式训练，但是报了这个错Runtimeerror: no rendezvous handler for TCP: / /，请问应该修改哪里才能解决呢



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/lemuria-wchen/DialogVED/issues/1",

"url": "https://github.com/lemuria-wchen/DialogVED/issues/1",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by gaokaizhi** [comment]
> 你好，能否具体一点，开发环境之类的，torch   ，cuda版本之类的，能否都贴出来一下---- 回复的原邮件 ***@***.***>发送日期2022年10月11日 09:30 ***@***.***> ***@***.***>主题[lemuria-wchen/DialogVED] windows系统分布式训练问题 (Issue #1) 您好，我是用单机多卡进行分布式训练，但是报了这个错Runtimeerror: no rendezvous handler for TCP: / /，请问应该修改哪里才能解决呢 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#1", "url": "#1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

我的环境，fairseq==0.9.0，torch==1.7.0，cuda==11.0.221,python==3.7.11，使用Windows系统

**Comment by lemuria-wchen** [comment]
可以先把torch版本改一下试试，按照下面的要求
python==3.7
torch==1.3.0
fairseq==0.9.0
tensorboardX==1.7
pytorch_transformers
sklearn
nltk==3.5

**Comment by gaokaizhi** [comment]
> 
您当时有在Windows上运行仓库中的代码吗？我在网上看到的说法是pytorch在Windows系统上无法并行的代码，放到Linux系统就可以跑了，大家都没有比较好的解决办法可以在Windows系统上正常并行化训练，这个好像和torch版本关系不是很大，不知道和fairseq0.9.0兼容的torch版本是多少呢？难道是fairseq和torch版本不兼容？但我看大家用fairseq0.9.0版本的也有使用高版本torch的，比如1.6版本的torch

**Comment by lemuria-wchen** [comment]
您好，我没有在windows上运行过这个代码，都是在linux上运行的。不过根据之前的测试，torch 版本过高运行这份代码会有问题的。上面那个环境是我测试过没有问题的版本
